### ISSUE TITLE
Does this support sensitivity analysis?

### ISSUE THREAD

**Issue by Ge0rges** [SciML/diffeqpy#103]
Hello,

I was wondering if this package supports the sensitivity analysis function of the original Julia package.

Specifically, can I run the Julia code below in python?

```
f1 = function (p)
  prob1 = remake(prob;p=p)
  sol = solve(prob1, Rosenbrock23(); saveat=collect(range(0, stop=duration, length=200)), maxiters=Int(1e6))
  [last(sol[1,:])]
end

sobol_result = GlobalSensitivity.gsa(f1, Sobol(), p_range, N=1000)
```

**Comment by ChrisRackauckas** [comment]
It doesn't import/export GlobalSensitivity.jl, so you'd have to directly use pyjulia calls to get GlobalSensitivity. But if you do, then it should work fine.
