### ISSUE TITLE
question: is this repository still under maintain?

### ISSUE THREAD

**Issue by Amos-Zhao** [SciML/diffeqpy#107]
![image](https://user-images.githubusercontent.com/20222480/208244502-efde9d2a-a017-4d24-a3c9-5d59b557aad8.png)
![image](https://user-images.githubusercontent.com/20222480/208244516-e48b1c49-0283-4e0b-8ffd-3665352c38ca.png)

**Comment by ChrisRackauckas** [comment]
Tests on master seem fine: https://github.com/SciML/diffeqpy/pull/108

Running tests against Python 3.11 to see if that broke anything: https://github.com/SciML/diffeqpy/pull/109

**Comment by Amos-Zhao** [comment]
great thanks

**Comment by ChrisRackauckas** [comment]
And Python 3.11 seems fine: https://github.com/SciML/diffeqpy/pull/109 So at least our tests don't see anything wrong. Any issue with need a reproducer.
