### ISSUE TITLE
problems with julia 1.9?

### ISSUE THREAD

**Issue by zingale** [SciML/diffeqpy#113]
I am trying the simple example:

```
from diffeqpy import de


def f(u,p,t):
    return -u

u0 = 0.5
tspan = (0., 1.)
prob = de.ODEProblem(f, u0, tspan)
sol = de.solve(prob)

print(sol)
```

on a machine with Fedora 38.  This has python 3.11 and Julia 1.9.  When I run this example, I get:
```
ERROR: Unable to dlopen(cxxpath) in parent!
Message: /lib64/libstdc++.so.6: cannot open shared object file: No such file or directory
```

If I try the same test on a machine with Fedora 37, which has python 3.11 but Julia 1.8, it runs fine.

Is there an incompatibility with Julia 1.9? or is there an addition setup needed?

This is with a fresh install of `DifferentialEquations.jl`.

**Comment by ChrisRackauckas** [comment]
I think this is generally a pyjulia issue, not a diffeqpy issue. This issue likely needs to be upstreamed to https://github.com/JuliaPy/pyjulia

**Comment by ChrisRackauckas** [comment]
Fixed!
