### ISSUE TITLE
diffeqpy GPU isn't automatically installing DiffEqGPU on Collab?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/diffeqpy#126]
https://colab.research.google.com/drive/1bnQMdNvg0AL-LyPcXBiH10jBij5QUmtY?usp=sharing

@LilithHafner do you happen to see what I may have done wrong? It's odd to me that it auto-installs DiffEq and MTK but not DiffEqGPU/CUDA when done the same way.

**Comment by LilithHafner** [comment]
This runs on `diffeqpy.install()` (and on initial load in the event that Julia is missing from the system)

https://github.com/SciML/diffeqpy/blob/42ce4d3fe7e6ffd620254b9cff9da4b039eecb9e/diffeqpy/install.jl#L3

and is where we install DiffEq and MTK.

Other packages can be added to that list (but I would not want to install and attempt to precompile Metal.jl or Cuda.jl on hardware that does not support those packages)

**Comment by ChrisRackauckas** [comment]
ahh I see. Yeah we should make separate `diffeqpy.install_cuda()`, `diffeqpy.install_amdgpu()`, etc.
