### ISSUE TITLE
DAE with Mass Matrix

### ISSUE THREAD

**Issue by vick2075** [SciML/diffeqpy#140]
**Question❓**

If you need help or have a general question, the primary online discussion venue for Julia is the [Discourse forum](https://discourse.julialang.org/).
Here, we only answer questions about internal design and implementation.

Hi,

I'm trying to solve DAE with mass matrix as per testset found here: https://archimede.uniba.it/~testset/problems/transamp.php
using the Fortran code: transamp.f and translated in Python using diffeqpy.

However, I'm having problem with either the formulation with diffeqpy or I'm using the wrong arguments for solver.

Can you please help me out?

I've attached my Python script.

Thanks
Vickram
[pyjultransistor.py.txt](https://github.com/SciML/diffeqpy/files/14779272/pyjultransistor.py.txt)

**Comment by ChrisRackauckas** [comment]
That looks generally correct. I haven't had a chance to run this yet though. What's the error that you're getting?

**Comment by vick2075** [comment]
> That looks generally correct. I haven't had a chance to run this yet though. What's the error that you're getting?

I can't figure out what the error is all about as it's very long. I've even tried autodiff=false as well but to no avail.
[error.pdf](https://github.com/SciML/diffeqpy/files/14874008/error.pdf)

**Comment by ChrisRackauckas** [comment]
Did you try doing the JIT compilation? That would make it move to the Julia side which would both speed it up and handle autodiff.

**Comment by vick2075** [comment]
> Did you try doing the JIT compilation? That would make it move to the Julia side which would both speed it up and handle autodiff.

Just did and here are the script and the error:
[error.pdf](https://github.com/SciML/diffeqpy/files/14898206/error.pdf)
[pyjultransistor.pdf](https://github.com/SciML/diffeqpy/files/14898207/pyjultransistor.pdf)

**Comment by ChrisRackauckas** [comment]
That's not the syntax. It takes the ODEProblem, see https://github.com/SciML/diffeqpy?tab=readme-ov-file#compilation-with-dejit-and-julia

**Comment by vick2075** [comment]
> That's not the syntax. It takes the ODEProblem, see https://github.com/SciML/diffeqpy?tab=readme-ov-file#compilation-with-dejit-and-julia

Still not good:
[error.pdf](https://github.com/SciML/diffeqpy/files/14901691/error.pdf)
[pyjultransistor.pdf](https://github.com/SciML/diffeqpy/files/14901692/pyjultransistor.pdf)

**Comment by vick2075** [comment]
I found the error:
At du[3] I had (U4/-Ub)/R4+alpha * fac1 instead of
    (U4-Ub)/R4+alpha*fac1

[pyjultransistor.pdf](https://github.com/SciML/diffeqpy/files/14902132/pyjultransistor.pdf)
This is the corrected script

Thanks for the helps!
