### ISSUE TITLE
Set tspan to be a array/list instead of range

### ISSUE THREAD

**Issue by niuyushuo** [SciML/diffeqpy#142]
Hi @ChrisRackauckas,

I am using diffeqpy to solve DAEs in my project. For my project, the tspan is an array/list with a fixed time step instead of just a time range. Could you add this feature? Thank you so much!

**Comment by ChrisRackauckas** [comment]
`tspan` is just the solver interval. If you want to save the output at a fixed time step, then just use `saveat = dt`.

If you really want to use a fixed time step, then set `adaptive=false` and `dt`. You can have more controls via using `tstops` as well. Note that if you do that, you may want to change the implicit handler to not rely on adaptivity, in particular `ImplicitEuler(nlsolve=NLNewton(check_div=false, always_new=true, relax=4/10,max_iter=100))` could be a good way to do it. However, it is very rare you need to actually solve at a fixed time step, and that voids the adaptivity of the nonlinear solver, which makes it less able to recover in difficult situations. Thus I highly recommend not doing this unless you really have to. If you simply are looking for the output to be at a fixed interval, that's different from stepping at a fixed interval, and the answer there is `saveat`.

**Comment by ChrisRackauckas** [comment]
Please feel free to continue the conversation, but closing as there isn't a feature to implement as this simply can use the existing options. See the full docs on the options here:

https://docs.sciml.ai/DiffEqDocs/stable/basics/common_solver_opts/

**Comment by niuyushuo** [comment]
@ChrisRackauckas Really appreciate your response!
