### ISSUE TITLE
Fix Julia and package versions installed by diffeqpy

### ISSUE THREAD

**Issue by mcarobene-id** [SciML/diffeqpy#145]
**Is your feature request related to a problem? Please describe.**

Relates to recently opened issues #143 and #144 . 

Diffeqpy automatically installs Julia and required Julia packages if it can't find these on the machine. Importing diffeqpy.de recently stopped working suddenly, it turns out due to diffeqpy automatically installing the most recent Julia version, which appears to have breaking changes. This brought to light the fact that the versions of Julia/packages are not being fixed for a given version of diffeqpy, which may cause unexpected bugs or changed behaviour.

**Describe the solution you’d like**

Versions for Julia and the required packages that are installed with each `from diffeqpy import _` should be pinned in the diffeqpy repo to ensure reproducible package behaviour when one installs a specific version of `diffeqpy`.

Fixing the version of Julia that gets installed by `diffeqpy` could be done in the `install_julia` step [here](https://github.com/SciML/diffeqpy/blob/master/diffeqpy/__init__.py#L15)
with e.g.
```
install_julia(version="1.10.5")
```
however specifying Julia package versions will likely be more complex.

**Describe alternatives you’ve considered**

Manually installing a specific version of Julia before using diffeqpy works well, however manually installing specific versions of the packages in my case did not work - diffeqpy updated to the most recent versions.

**EDIT:** I'm finding that manually installing Julia 1.10.5 does work for me in a docker image, but doesn't work locally. I do not know why this is different, but the reason this doesn't work locally is that in the `from juliacall import Main` line of `diffeqpy.__init__`, juliacall uses `juliapkg.executable()` which [installs the most recent Julia](https://github.com/JuliaPy/pyjuliapkg/blob/main/src/juliapkg/deps.py#L300) even if there's an existing version

**Comment by ChrisRackauckas** [comment]
Done in v2.4.2 https://pypi.org/manage/project/diffeqpy/release/2.4.2/

**Comment by mcarobene-id** [comment]
Thanks for the quick attention in fixing the Julia version @ChrisRackauckas 🌟 Would it be possible to additionally look into fixing the versions of the downstream Julia packages that get installed for the different components of diffeqpy?

**Comment by ChrisRackauckas** [comment]
We could set a fixed manifest for diffeqpy. I'm not sure that has been an issue so far though?
