### ISSUE TITLE
SDE simulation fails with `de.jit`

### ISSUE THREAD

**Issue by himoto** [SciML/diffeqpy#148]
**Describe the bug 🐞**

The sample SDE code in the README (**Systems of SDEs with Diagonal Noise**) fails with `de.jit`, but doesn't fail without it.

**Minimal Reproducible Example 👇**

```python
import matplotlib.pyplot as plt
from diffeqpy import de
```

- With `de.jit`
```python
def f(du,u,p,t):
    x, y, z = u
    sigma, rho, beta = p
    du[0] = sigma * (y - x)
    du[1] = x * (rho - z) - y
    du[2] = x * y - beta * z

def g(du,u,p,t):
    du[0] = 0.3*u[0]
    du[1] = 0.3*u[1]
    du[2] = 0.3*u[2]

u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.jit(de.SDEProblem(f, g, u0, tspan, p))
sol = de.solve(prob)

# Now let's draw a phase plot

us = de.stack(sol.u)
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(us[0,:],us[1,:],us[2,:])
plt.show()
```
![with_jit](https://github.com/user-attachments/assets/e43a615d-1183-41be-aa53-87d341b7c1af)

- Without `de.jit`
```python
def f(du,u,p,t):
    x, y, z = u
    sigma, rho, beta = p
    du[0] = sigma * (y - x)
    du[1] = x * (rho - z) - y
    du[2] = x * y - beta * z

def g(du,u,p,t):
    du[0] = 0.3*u[0]
    du[1] = 0.3*u[1]
    du[2] = 0.3*u[2]

u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.SDEProblem(f, g, u0, tspan, p)
sol = de.solve(prob)

# Now let's draw a phase plot

us = de.stack(sol.u)
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(us[0,:],us[1,:],us[2,:])
plt.show()
```
![without_jit](https://github.com/user-attachments/assets/2f01c6ea-0e67-4418-9b80-2a4954fedb9c)

**Environment:**
- OS: macOS Sequoia version 15.1
- Chip: Apple M1 Max
- Python version: 3.12.7
- diffeqpy version: 2.4.2
- Julia version: 1.10.6
```bash
julia> Pkg.status()
Status `~/.julia/environments/diffeqpy/Project.toml`
  [0c46a032] DifferentialEquations v7.15.0
  [961ee093] ModelingToolkit v9.49.0
  [6099a3de] PythonCall v0.9.23
```

**Comment by himoto** [comment]
I have found that the jitted SDE problem works after downgrading [ModelingToolkit](https://github.com/SciML/ModelingToolkit.jl) to v9.40.0.

Code:
```python
def f(du,u,p,t):
    x, y, z = u
    sigma, rho, beta = p
    du[0] = sigma * (y - x)
    du[1] = x * (rho - z) - y
    du[2] = x * y - beta * z

def g(du,u,p,t):
    du[0] = 0.3*u[0]
    du[1] = 0.3*u[1]
    du[2] = 0.3*u[2]

u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.jit(de.SDEProblem(f, g, u0, tspan, p))
sol = de.solve(prob)

# Now let's draw a phase plot

us = de.stack(sol.u)
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(us[0,:],us[1,:],us[2,:])
plt.show()
```
![with_jit_9400](https://github.com/user-attachments/assets/bd9b9ca5-dada-4b6c-bbc0-b163a4312f22)

Environment:
```bash
(@diffeqpy) pkg> status
Status `~/.julia/environments/diffeqpy/Project.toml`
  [0c46a032] DifferentialEquations v7.15.0
⌃ [961ee093] ModelingToolkit v9.40.0
  [6099a3de] PythonCall v0.9.23
Info Packages marked with ⌃ have new versions available and may be upgradable.
```

ModelingToolkit v9.40.1 is causing the problem. Therefore, I think some changes made between 9.40.0 and 9.40.1 are critical for this issue.

**Comment by AayushSabharwal** [comment]
It's just callable parameters and allowing `nothing` to be passed as `u0` to `ODEProblem`

**Comment by AayushSabharwal** [comment]
![image](https://github.com/user-attachments/assets/cb9d0723-424c-4a03-ad17-088e83112976)

MTK seems to simulate this fine?

**Comment by ChrisRackauckas** [comment]
Yeah but something happened to the symbolic tracing of the Python code. It's worth recreating.

**Comment by AayushSabharwal** [comment]
I'll lookup how this works through python.

**Comment by ChrisRackauckas** [comment]
It just traces the Python code, or at least it used to.

**Comment by AayushSabharwal** [comment]
I see, yeah. I'm unfamiliar with how python interop works, but this looks like it's just exposing Julia with basically nothing existing in python. I'll reproduce this with plain julia and `modelingtoolkitize`.

**Comment by AayushSabharwal** [comment]
The problem is that `complete` reorders parameters, so https://github.com/SciML/diffeqpy/blob/af3d974a881647bc4f5b860ea33c9d152db36056/diffeqpy/de.py#L5 doesn't work because when re-creating the problem from the system it passes the `p` vector assuming it's in the same order. If we don't care for `MTKParameters`, this can be solved with `split = false`. If it's something we want to support, then a new question comes up: is setting the defaults of the modelingtoolkitized system to the values from the problem part of the contract of `modelingtoolkitize`? If so, `modelingtoolkitize(::SDEProblem)` doesn't do this. After fixing that, we'd need to change the python wrapper to not pass `u0` and `p` when re-creating the problem so that it uses defaults.

**Comment by AayushSabharwal** [comment]
https://docs.sciml.ai/ModelingToolkit/stable/tutorials/modelingtoolkitize/#What-is-modelingtoolkitize?
We document `modelingtoolkitize` setting defaults. So the latter approach seems best to me.

**Comment by ChrisRackauckas** [comment]
>  If it's something we want to support, then a new question comes up: is setting the defaults of the modelingtoolkitized system to the values from the problem part of the contract of modelingtoolkitize?

Yes we should do that.
