### ISSUE TITLE
Is that faster for a simple linear ode with periodic coefficients compared to Odeint?

### ISSUE THREAD

**Issue by falematte** [SciML/diffeqpy#53]
As in the title ;)

**Comment by ChrisRackauckas** [comment]
The tests in http://juliadiffeq.org/2018/04/30/Jupyter.html show it to be a lot faster (about 10x) than Numba-compiled odeint integration on a different system. You can try it on a simple linear ODE and see if you get similar results.

**Comment by ChrisRackauckas** [comment]
Use the new `fast_prob = de.jit(prob)`
