### ISSUE TITLE
using numba: No matching definition for argument type(s) float64, pyobject, float64

### ISSUE THREAD

**Issue by FLMuller** [SciML/diffeqpy#61]
Using numba as per the examples give, a warning; 

"NumbaWarning: Function "numba_f" was compiled in object mode without forceobj=True.

File "plop.py", line 39:
@jit
def numba_f(u,p,t):
^

  state.func_ir.loc))
c:\flmapps\python37\lib\site-packages\numba\object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
this warning can be avoided using the forceobj=true flag in jit, but the numba guide indicates that this results in significantly lower performance:

"If true, nopython forces the function to be compiled in nopython mode. If not possible, compilation will raise an error.

If true, forceobj forces the function to be compiled in object mode. Since object mode is slower than nopython mode, this is mostly useful for testing purposes."

When trying to inform Jit of the types eg: 

@jit('float64(float64,float64,float64)')
def numba_f(u,p,t):
    return -u+t**2

we get an error from the numba dispach system:

Traceback (most recent call last):

  File "C:\flmapps\Python37\FLM\test\plop.py", line 43, in <module>
    sol = de.solve(prob)

  File "c:\flmapps\python37\lib\site-packages\numba\dispatcher.py", line 574, in _explain_matching_error
    raise TypeError(msg)

TypeError: No matching definition for argument type(s) float64, pyobject, float64

It appeas that the function defined is being accessed with the middle parameter a pyobject, rather then the requested float64. No matter how I define the variuable U0

prob = de.ODEProblem(numba_f,np.float64(u0), tspan)
sol = de.solve(prob)

the solver persists in using a pyobject...

I am using a freshly installed python37, and JuliaPro. the juliainit file records the actions taken to get julia pro to work python and diffeq (note I had to reinstall the Pkg from the pyton command prompt, even though I allready had installed them in JP, as using julia.py reverts to the .julia userfolder, not the .juliapro userfolder...) the juliainit.zip gives the actions I had to complete to link to julia and diffeqsolver.jl))

[plop.zip](https://github.com/SciML/diffeqpy/files/4492232/plop.zip)
[JuliaInit.zip](https://github.com/SciML/diffeqpy/files/4492237/JuliaInit.zip)

**Comment by ChrisRackauckas** [comment]
Xref https://github.com/SciML/diffeqpy/issues/60 as a better way to handle this. I think what we should do instead is start showcasing the use of ModelingToolkit for direct code generation, since the Numba issues here seem somewhat hard to avoid.

**Comment by FLMuller** [comment]
New to Julia.... #60 hack seems to move a little beyond the obvious.... but I ll have a look at this modelling toolbox. Could you explain why only the parameter is affected?

**Comment by ChrisRackauckas** [comment]
I honestly don't know why only the parameter is effected here.

**Comment by FLMuller** [comment]
Thanks Chris, I have sorted it now, the issues was that the problem function must be defined with arrays for u and p and a float for t. the function needs to return a float array as well. 

with numba you cannot define the parameters as python-'lists' e.g. p=[1,2,3]

the parameters must be numpy.array's

example: 

from numba import jit
@jit('float64[:](float64[:],float64[:],float64)')
def numba_f(u,p,t):
    #this generates an output with the same type as u, 
    #but does not copy u...
    du=u*0 
    
    du[0]=-u[0]+t**2
    du[1]=p[1]
    print("numbaF:",t,du)
    return du

u0 = np.array([0.5,0.5])
tspan = (0.,3.)
p=np.array([0.1,2])

print("using numba2")
rtn=numba_f(u0,p,tspan[0])

prob = de.ODEProblem(numba_f,u0, tspan,p)
sol4 = de.solve(prob)
plt.plot(sol4.t,sol4.u,'mo:')
plt.show()

**Comment by ChrisRackauckas** [comment]
Awesome. I added a note to the README saying that NumPy arrays are needed with Numba.
