### ISSUE TITLE
Getting Assertion failed error message

### ISSUE THREAD

**Issue by OrbitalMechanic** [SciML/diffeqpy#64]
I was able to install successfully diffeqpy on my Mac Pro (2019)  running Mac OS X ver. 10.15.4 (Catalina). I'm running Python version 3.7.6 from the Anaconda distribution.  The problem I'm having is when I run the test program test_ode.py (see the attached file test_ode.py.txt), I get an "Assertion failed error message (see the attached file diffeqpy_run.txt). 

Please advise.

Sam Dupree.

[diffeqpy_run.txt](https://github.com/SciML/diffeqpy/files/4532593/diffeqpy_run.txt)
[test_ode.py.txt](https://github.com/SciML/diffeqpy/files/4532594/test_ode.py.txt)

**Comment by ChrisRackauckas** [comment]
Did you get Julia from the generic binaries? https://julialang.org/downloads/ This looks like an LLVM issue, so possibly if you built locally it could be the wrong version of LLVM.

**Comment by OrbitalMechanic** [comment]
To my knowledge I got them from  https://julialang.org/downloads/.

**Comment by ChrisRackauckas** [comment]
Fixed by the transition to PythonCall
