### ISSUE TITLE
Is it possible to pass the gradient from PyTorch to Julia to accelerate sensitivity analysis?

### ISSUE THREAD

**Issue by jiweiqi** [SciML/diffeqpy#66]
The RHS of the equation [dx = F(x, p)] is written in PyTorch, so that I have access to the Jacobian and the gradient of state variables to all of the model parameters. Can I pass the gradient information to accelerate the sensitivity analysis? Specifically,
* Jacobian matrix ( df/dx )
* Jacobian of the parameters (dF/dp)

**Comment by ChrisRackauckas** [comment]
You can set the `vjp` in the `ODEFunction` constructor, and that would accelerate it. https://docs.sciml.ai/latest/analysis/sensitivity/#Adjoint-Sensitivity-Analysis-via-adjoint_sensitivities-(Backpropogation)-1 + https://docs.sciml.ai/latest/features/performance_overloads/#ODEFunction-1 is the documentation on this (though `vjp` is a new option that doesn't seem to be documented yet!).

>Jacobian matrix ( df/dx )
> Jacobian of the parameters (dF/dp)

You wouldn't want to compute those, you'd want to supply a method for computing the vector-jacobian product directly, which is provided by PyTorch. It would be good to get an example up and running...

**Comment by jiweiqi** [comment]
I am really a new Julia user, maybe it is a too simple question: in the document https://docs.sciml.ai/latest/analysis/sensitivity/#Adjoint-Sensitivity-Analysis-via-adjoint_sensitivities-(Backpropogation)-1, I have the following bugs

```
dg(out,u, i) = (out.=1.0.-u)
ts = [0.0,0.2,0.5,0.7]
res = adjoint_sensitivities(sol,Vern9(),dg,ts,abstol=1e-9,reltol=1e-6)
```

then it seems that the definition of dg has something wrong:
```
MethodError: no method matching dg(::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64)
Closest candidates are:
  dg(::Any, ::Any, ::Any) at In[26]:1
  dg(::Any, ::Any) at In[25]:1
```

**Comment by ChrisRackauckas** [comment]
There was a docs typo. It should be `dg(out,u,p,t,i) = (out.=1.0.-u)`

**Comment by ChrisRackauckas** [comment]
Did you find an adequate solution here? I think we should add it to the docs if you did.

**Comment by jiweiqi** [comment]
I haven't figure out yet. Calling python functions from Julia seems to be not a robust solution for me. Instead, I plan to re-implement the physical model using Julia, that will make life easier.

**Comment by ChrisRackauckas** [comment]
Yeah, that's probably the easier route for now. Let me know if you need any help: I think I recall you're in the chatrooms so see you there.
