### ISSUE TITLE
Calling the differential fucntion for ODE solving from a class

### ISSUE THREAD

**Issue by GrandadsJumper** [SciML/diffeqpy#80]
This is generically my code:

from diffeqpy import de
class A():
    def __init__(self):
        self.run()

    def run(self):     
        tspan = (0, 1, 2)
        y=[0, 0]

        prob = de.ODEProblem(self.ODE_function, y, tspan)
        sol = de.solve(prob, saveat=0.01)
    
    def ODE_function(self, y, p, t):
        #Code that creates differentials from new y values.
        return [#list of differentials]

A()

______________
I get this error:
    sol = de.solve(prob, saveat=0.01)
TypeError: ODE_function() takes 4 positional arguments but 5 were given

I udnerstand the error code but havent strayed from the ODE example except in using a classed fucntion, is this something the module cant fathom ?

**Comment by ChrisRackauckas** [comment]
I don't know this whole `self` thing. `def ODE_function(y, p, t):` should be fine.

**Comment by GrandadsJumper** [comment]
self and class are what make python an object orientated language; i dont believe julia is object orientated. 

I found changing the ODE_function(self, y, p, t) --> ODE_function(self, *args) and adding in the following to the beggining of the function allows it to work:

        llst = []
        for arg in args:
            llst.append(arg)

        y = llst[0]
        p = llst[1]
        t = llst[2]

I think the issue was that julia thinks "self" is the du parameter and decides to give back du, u, p and t (instead of just the requested u,p and t) because the "self" parameter makes the function seem to requrie 4 variables.
