### ISSUE TITLE
the following import in python "from diffeqpy import de" takes 1-2 minutes to complete

### ISSUE THREAD

**Issue by GrandadsJumper** [SciML/diffeqpy#81]
Im running Julia 1.5.3 and Python 3.7 through the PyCharm IDE. 

I set up as per the isntructions on the repository main page, the module eventually imports and the functions work as described, just the time to import it is something I've not seen before; is this a standard wait time everyone else experiences with this module or do I have a problem with my setup somewhere?

Thanks :)

**Comment by ChrisRackauckas** [comment]
The first time you do the setup code, it will compile the entire set of Julia libraries. I don't know if it sends the message from Julia to Python about the fact that it's running precompilation. (Note that precompilation times for these libraries is an order of magnitude faster on Julia v1.6)

**Comment by GrandadsJumper** [comment]
Thank you for your help again.

I can confirm it is the precompile of DifferentialEquations in julia which causes the long wait time. 

No message is passed to python, the console simply hangs until julia completes the compilation  of Diff..Eq.

I cant seem to find a release for V1.6, would you happen to have a link ?
