### ISSUE TITLE
Installing diffeqpy in local Julia environment

### ISSUE THREAD

**Issue by tinosulzer** [SciML/diffeqpy#83]
I am trying to write a script to automatically install `julia` and `diffeqpy`:
```python3
import julia
from julia import Pkg
import diffeqpy

Pkg.activate(".") # use local environment
julia.install()
diffeqpy.install()
```
However, when running the final line, I get
```
   Updating registry at `~/.julia/registries/General`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
```
i.e. it installs to the default v1.5 instead of my local environment. Is there a way to tell `diffeqpy` where to install?

**Comment by ChrisRackauckas** [comment]
I'll have to defer to @tkf on this one.

**Comment by tinosulzer** [comment]
Does diffeqpy.install() just install the required Julia packages, and if so do I need to do it if I have a Project.toml for my local environment?

**Comment by ChrisRackauckas** [comment]
It adds the packages if they aren't already in your active environment. The code it runs is: https://github.com/SciML/diffeqpy/blob/master/diffeqpy/install.jl

**Comment by ChrisRackauckas** [comment]
I think what would need to be done is we'd need to have a way in https://github.com/SciML/diffeqpy/blob/master/diffeqpy/__init__.py#L7-L11 to pass down the environment

**Comment by ChrisRackauckas** [comment]
It installs to a local environment now
