### ISSUE TITLE
Does this library implement inplace=False ODEProblems?

### ISSUE THREAD

**Issue by alexlenail** [SciML/diffeqpy#91]
The README [mentions](https://github.com/SciML/diffeqpy#in-place-mutating-form) that this library supports the inplace=True variant of ODEProblem, but does not mention whether inplace=False is supported. 

- If it is not supported, this issue could be renamed to: "Support ODEProblem with inplace=False"
- If it is not supported and we would prefer to keep it that way, the README should at least make note of that. 
- If it is supported and I just missed it, the README/docs should mention how to get this functionality.

**Comment by ChrisRackauckas** [comment]
The first two examples are in the inplace=False form.
