### ISSUE TITLE
Converting python code that uses diffeqpy to executable file via Pyinstaller

### ISSUE THREAD

**Issue by kongjy94** [SciML/diffeqpy#95]
Hi all,

I am currently facing an issue with converting my python (.py) file to an executable (.exe) file via Pyinstaller. The error brings me to the diffeqpy package/Julia but I am not sure how to fix it. My python code works fine.

The error is “subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1”.
 
I will appreciate if you can assist me on this matter.

**Comment by ChrisRackauckas** [comment]
@tkf is this possible?
