### ISSUE TITLE
FYI: Support PythonCall.jl

### ISSUE THREAD

**Issue by PallHaraldsson** [SciML/diffeqpy#97]
https://cjdoris.github.io/PythonCall.jl/stable/juliacall/#Installation

I checked it myself and it does download Julia for you, as claimed (1.7) and its example works. So I tried with your package to see if it worked too, but got some PyCall error, understandably. I just think if might help your users to not have to download or know much about Julia. I've not used PythonCall extensively myself. It does have a larger startup cost (currently, I have a PR coming up bringing down to 3.06 sec. maybe further).

```
julia> @time using PythonCall
  4.431433 seconds (2.88 M allocations: 164.448 MiB, 1.13% gc time, 82.64% compilation time)

julia> @time using PyCall
  0.978491 seconds (963.43 k allocations: 62.176 MiB, 1.16% gc time, 73.61% compilation time)

compared to:

$ ~/julia-1.7.0/bin/julia -O0 --compile=min

julia> @time using PythonCall
  1.051802 seconds (816.71 k allocations: 58.820 MiB, 1.40% gc time, 17.52% compilation time)

julia> @time using PyCall
  0.630133 seconds (484.69 k allocations: 35.356 MiB, 52.99% compilation time)
```

PyCall didn't work right away, I had to build it.

**Comment by sibyjackgrove** [comment]
@PallHaraldsson Have you compared JuliaCall with PyJulia? Diffeqpy uses PyJulia for calling Julia from Python.

**Comment by PallHaraldsson** [comment]
I haven't used PythonCall much but it compares to PyJulia. I realize PyJulia is currently used, I'm not sure PythonCall could be a non-default option, might be confusing to have two options. It might be better to support PythonCall only.

**Comment by ChrisRackauckas** [comment]
Having two options is untenable. Really it needs to be one well-supported one. If it's just the Julia installation, right now it seems like pyjulia with https://github.com/JuliaPy/pyjulia/issues/473 might be best. I would be happy if @00sapo could help us figure out a nice solution for automating the diffeqpy installation.

**Comment by ChrisRackauckas** [comment]
That's a gigantic change. If you're willing to do all of that work then go for it.

**Comment by jlapeyre** [comment]
There are very big differences between PythonCall and PyJulia. The fact that one downloads julia automatically is a minor detail in comparison. It shouldn't determine the choice--- like buying car because you like the cup holder. For example, the script that Chris linked to or something like it would be reasonable for automatic downloading.

**Comment by ChrisRackauckas** [comment]
Now done via PythonCall
